const common = {
  title: {
    tc_name: "香港電車 到站時間",
    en_name: "Hong Kong Tramways ETA",
  },
  auto: {
    tc_name: "自動",
    en_name: "Auto",
  },
  bound: {
    tc_name: "方向",
    en_name: "Bound",
  },
  station: {
    tc_name: "電車站",
    en_name: "Tram Stop",
  },
  eastbound: {
    tc_name: "東行",
    en_name: "Eastbound",
  },
  westbound: {
    tc_name: "西行",
    en_name: "Westbound",
  },
  etaAlert: {
    tc_name: "到站時間資訊每10秒自動更新，資料只供參考。",
    en_name:
      "ETA information will be refresh every 10 seconds, reference data only.",
  },
  min: {
    tc_name: "分鐘",
    en_name: "min",
  },
  arrived: {
    tc_name: "已到達",
    en_name: "Arrived",
  },
  lastTram: {
    tc_name: "最後班次",
    en_name: "Last Tram",
  },
};

const hkTramStops = {
  SKT: {
    bound: "W",
    en_name: "Shau Kei Wan Terminus",
    tc_name: "筲箕灣總站",
    status: "1",
    lag: "",
    lon: "",
  },
  "02W": {
    bound: "W",
    en_name: "Chai Wan Road",
    tc_name: "柴灣道",
    status: "1",
    lag: "",
    lon: "",
  },
  "04W": {
    bound: "W",
    en_name: "Sun Sing Street",
    tc_name: "新成街",
    status: "1",
    lag: "",
    lon: "",
  },
  "06W": {
    bound: "W",
    en_name: "Hoi Foo Street",
    tc_name: "海富街",
    status: "1",
    lag: "",
    lon: "",
  },
  "08W": {
    bound: "W",
    en_name: "Holy Cross Path",
    tc_name: "聖十字徑",
    status: "1",
    lag: "",
    lon: "",
  },
  "10W": {
    bound: "W",
    en_name: "Tai Hong Street",
    tc_name: "太康街",
    status: "1",
    lag: "",
    lon: "",
  },
  "12W": {
    bound: "W",
    en_name: "Tai Koo Shing Road",
    tc_name: "太古城道",
    status: "1",
    lag: "",
    lon: "",
  },
  "14W": {
    bound: "W",
    en_name: "Kornhill",
    tc_name: "康山",
    status: "1",
    lag: "",
    lon: "",
  },
  "16W": {
    bound: "W",
    en_name: "Shipyard Lane",
    tc_name: "船塢里",
    status: "1",
    lag: "",
    lon: "",
  },
  "18W": {
    bound: "W",
    en_name: "Mount Parker Road",
    tc_name: "柏架山道",
    status: "1",
    lag: "",
    lon: "",
  },
  "20W": {
    bound: "W",
    en_name: "Finnie Street",
    tc_name: "芬尼街",
    status: "1",
    lag: "",
    lon: "",
  },
  "22W": {
    bound: "W",
    en_name: "Java Road",
    tc_name: "渣華道",
    status: "1",
    lag: "",
    lon: "",
  },
  "24W": {
    bound: "W",
    en_name: "Healthy Street East",
    tc_name: "健康東街",
    status: "1",
    lag: "",
    lon: "",
  },
  "26W": {
    bound: "W",
    en_name: "Healthy Street West",
    tc_name: "健康西街",
    status: "1",
    lag: "",
    lon: "",
  },
  "28W": {
    bound: "W",
    en_name: "Tin Chiu Street",
    tc_name: "電照街",
    status: "1",
    lag: "",
    lon: "",
  },
  "30W": {
    bound: "W",
    en_name: "Shu Kuk Street",
    tc_name: "書局街",
    status: "1",
    lag: "",
    lon: "",
  },
  NPT: {
    bound: "W",
    en_name: "North Point Terminus",
    tc_name: "北角總站",
    status: "1",
    lag: "",
    lon: "",
  },
  "32W": {
    bound: "W",
    en_name: "North Point Road",
    tc_name: "北角道",
    status: "1",
    lag: "",
    lon: "",
  },
  "34W": {
    bound: "W",
    en_name: "Fortress Hill",
    tc_name: "炮台山",
    status: "1",
    lag: "",
    lon: "",
  },
  "36W": {
    bound: "W",
    en_name: "Jupiter Street",
    tc_name: "木星街",
    status: "1",
    lag: "",
    lon: "",
  },
  "38W": {
    bound: "W",
    en_name: "Lau Li Street",
    tc_name: "琉璃街",
    status: "1",
    lag: "",
    lon: "",
  },
  "40W": {
    bound: "W",
    en_name: "Lau Sin Street",
    tc_name: "留仙街",
    status: "1",
    lag: "",
    lon: "",
  },
  "42W": {
    bound: "W",
    en_name: "Victoria Park",
    tc_name: "維多利亞公園",
    status: "1",
    lag: "",
    lon: "",
  },
  "44W": {
    bound: "W",
    en_name: "Shelter Street",
    tc_name: "信德街",
    status: "1",
    lag: "",
    lon: "",
  },
  CBT: {
    bound: "W",
    en_name: "Causeway Bay Terminus",
    tc_name: "銅鑼灣總站",
    status: "1",
    lag: "",
    lon: "",
  },
  "46W": {
    bound: "W",
    en_name: "Pennington Street",
    tc_name: "邊寧頓街",
    status: "1",
    lag: "",
    lon: "",
  },
  "48W": {
    bound: "W",
    en_name: "Paterson Street",
    tc_name: "百德新街",
    status: "1",
    lag: "",
    lon: "",
  },
  105: {
    bound: "W",
    en_name: "Foo Ming Street",
    tc_name: "富明街",
    status: "1",
    lag: "",
    lon: "",
  },
  106: {
    bound: "W",
    en_name: "Leighton Road",
    tc_name: "禮頓道",
    status: "1",
    lag: "",
    lon: "",
  },
  107: {
    bound: "W",
    en_name: "Broadwood Road",
    tc_name: "樂活道",
    status: "1",
    lag: "",
    lon: "",
  },
  108: {
    bound: "W",
    en_name: "Wong Nai Chung Road",
    tc_name: "黃泥涌道",
    status: "1",
    lag: "",
    lon: "",
  },
  HVT_K: {
    bound: "W",
    en_name: "Happy Valley Terminus",
    tc_name: "跑馬地總站",
    status: "1",
    lag: "",
    lon: "",
  },
  109: {
    bound: "W",
    en_name: "Hong Kong Cemetery",
    tc_name: "香港墳場",
    status: "1",
    lag: "",
    lon: "",
  },
  110: {
    bound: "W",
    en_name: "Queen's Road East",
    tc_name: "皇后大道東",
    status: "1",
    lag: "",
    lon: "",
  },
  111: {
    bound: "W",
    en_name: "Morrison Hill Road",
    tc_name: "摩利臣山道",
    status: "1",
    lag: "",
    lon: "",
  },
  112: {
    bound: "W",
    en_name: "Tin Lok Lane",
    tc_name: "天樂里",
    status: "1",
    lag: "",
    lon: "",
  },
  "50W": {
    bound: "W",
    en_name: "Canal Road West",
    tc_name: "堅拿道西",
    status: "1",
    lag: "",
    lon: "",
  },
  "52W": {
    bound: "W",
    en_name: "Tonnochy Road",
    tc_name: "杜老誌道",
    status: "1",
    lag: "",
    lon: "",
  },
  "54W": {
    bound: "W",
    en_name: "Burrows Street",
    tc_name: "巴路士街",
    status: "1",
    lag: "",
    lon: "",
  },
  "56W": {
    bound: "W",
    en_name: "O'Brien Road",
    tc_name: "柯布連道",
    status: "1",
    lag: "",
    lon: "",
  },
  "58W": {
    bound: "W",
    en_name: "Swatow Street",
    tc_name: "汕頭街",
    status: "1",
    lag: "",
    lon: "",
  },
  "60W": {
    bound: "W",
    en_name: "Gresson Street",
    tc_name: "機利臣街",
    status: "1",
    lag: "",
    lon: "",
  },
  "62W": {
    bound: "W",
    en_name: "Arsenal Street",
    tc_name: "軍器廠街",
    status: "1",
    lag: "",
    lon: "",
  },
  "64W": {
    bound: "W",
    en_name: "Admiralty MTR Station",
    tc_name: "金鐘港鐵站",
    status: "1",
    lag: "",
    lon: "",
  },
  "66W": {
    bound: "W",
    en_name: "Cotton Tree Drive",
    tc_name: "紅棉道",
    status: "1",
    lag: "",
    lon: "",
  },
  "68W": {
    bound: "W",
    en_name: "Bank Street",
    tc_name: "銀行街",
    status: "1",
    lag: "",
    lon: "",
  },
  "70W": {
    bound: "W",
    en_name: "Pedder Street",
    tc_name: "畢打街",
    status: "1",
    lag: "",
    lon: "",
  },
  "72W": {
    bound: "W",
    en_name: "Pottinger Street",
    tc_name: "砵甸乍街",
    status: "1",
    lag: "",
    lon: "",
  },
  "74W": {
    bound: "W",
    en_name: "Gilman Street",
    tc_name: "機利文街",
    status: "1",
    lag: "",
    lon: "",
  },
  "76W": {
    bound: "W",
    en_name: "Man Wah Lane",
    tc_name: "文華里",
    status: "1",
    lag: "",
    lon: "",
  },
  WM: {
    bound: "W",
    en_name: "Western Market Terminus",
    tc_name: "上環 (西港城) 總站",
    status: "1",
    lag: "",
    lon: "",
  },
  "78W": {
    bound: "W",
    en_name: "Macau Ferry Terminal",
    tc_name: "港澳碼頭",
    status: "1",
    lag: "",
    lon: "",
  },
  "80W": {
    bound: "W",
    en_name: "Connaught Road West",
    tc_name: "干諾道西",
    status: "1",
    lag: "",
    lon: "",
  },
  "82W": {
    bound: "W",
    en_name: "Sutherland Street",
    tc_name: "修打蘭街",
    status: "1",
    lag: "",
    lon: "",
  },
  "84W": {
    bound: "W",
    en_name: "Eastern Street",
    tc_name: "東邊街",
    status: "1",
    lag: "",
    lon: "",
  },
  "86W": {
    bound: "W",
    en_name: "Western Street",
    tc_name: "西邊街",
    status: "1",
    lag: "",
    lon: "",
  },
  "88W": {
    bound: "W",
    en_name: "Water Street",
    tc_name: "水街",
    status: "1",
    lag: "",
    lon: "",
  },
  "90W": {
    bound: "W",
    en_name: "Whitty Street",
    tc_name: "屈地街",
    status: "1",
    lag: "",
    lon: "",
  },
  "92W": {
    bound: "W",
    en_name: "Hill Road",
    tc_name: "山道",
    status: "1",
    lag: "",
    lon: "",
  },
  "94W": {
    bound: "W",
    en_name: "Whitty Street Depot",
    tc_name: "屈地街電車廠",
    status: "1",
    lag: "",
    lon: "",
  },
  "96W": {
    bound: "W",
    en_name: "Queen's Road West",
    tc_name: "皇后大道西",
    status: "1",
    lag: "",
    lon: "",
  },
  "98W": {
    bound: "W",
    en_name: "Kennedy Town Praya",
    tc_name: "堅尼地城海傍",
    status: "1",
    lag: "",
    lon: "",
  },
  "100W": {
    bound: "W",
    en_name: "Sands Street",
    tc_name: "山市街",
    status: "1",
    lag: "",
    lon: "",
  },
  "102W": {
    bound: "W",
    en_name: "Smithfield",
    tc_name: "士美菲路",
    status: "1",
    lag: "",
    lon: "",
  },
  "104W": {
    bound: "W",
    en_name: "Davis Street",
    tc_name: "爹核士街",
    status: "1",
    lag: "",
    lon: "",
  },

  "101E": {
    bound: "E",
    en_name: "Chai Wan Road",
    tc_name: "柴灣道",
    status: "1",
    lag: "",
    lon: "",
  },
  "99E": {
    bound: "E",
    en_name: "Nam Hong Street",
    tc_name: "南康街",
    status: "1",
    lag: "",
    lon: "",
  },
  "97E": {
    bound: "E",
    en_name: "Sai Wan Ho Depot",
    tc_name: "西灣河電車廠",
    status: "1",
    lag: "",
    lon: "",
  },
  "95E": {
    bound: "E",
    en_name: "Hoi Foo Street",
    tc_name: "海富街",
    status: "1",
    lag: "",
    lon: "",
  },
  "93E": {
    bound: "E",
    en_name: "Tai On Street",
    tc_name: "太安街",
    status: "1",
    lag: "",
    lon: "",
  },
  "91E": {
    bound: "E",
    en_name: "Tai Hong Street",
    tc_name: "太康街",
    status: "1",
    lag: "",
    lon: "",
  },
  "89E": {
    bound: "E",
    en_name: "Tai Koo Shing Road",
    tc_name: "太古城道",
    status: "1",
    lag: "",
    lon: "",
  },
  "87E": {
    bound: "E",
    en_name: "Kornhill",
    tc_name: "康山",
    status: "1",
    lag: "",
    lon: "",
  },
  "85E": {
    bound: "E",
    en_name: "Shipyard Lane",
    tc_name: "船塢里",
    status: "1",
    lag: "",
    lon: "",
  },
  "83E": {
    bound: "E",
    en_name: "Mount Parker Road",
    tc_name: "柏架山道",
    status: "1",
    lag: "",
    lon: "",
  },
  "81E": {
    bound: "E",
    en_name: "Finnie Street",
    tc_name: "芬尼街",
    status: "1",
    lag: "",
    lon: "",
  },
  "79E": {
    bound: "E",
    en_name: "Java Road",
    tc_name: "渣華道",
    status: "1",
    lag: "",
    lon: "",
  },
  "77E": {
    bound: "E",
    en_name: "Healthy Street East",
    tc_name: "健康東街",
    status: "1",
    lag: "",
    lon: "",
  },
  "75E": {
    bound: "E",
    en_name: "Healthy Street West",
    tc_name: "健康西街",
    status: "1",
    lag: "",
    lon: "",
  },
  "73E": {
    bound: "E",
    en_name: "Tin Chiu Street",
    tc_name: "電照街",
    status: "1",
    lag: "",
    lon: "",
  },
  "71E": {
    bound: "E",
    en_name: "Shu Kuk Street",
    tc_name: "書局街",
    status: "1",
    lag: "",
    lon: "",
  },
  "69E": {
    bound: "E",
    en_name: "North Point Road",
    tc_name: "北角道",
    status: "1",
    lag: "",
    lon: "",
  },
  "67E": {
    bound: "E",
    en_name: "Chun Yeung Street",
    tc_name: "春秧街",
    status: "1",
    lag: "",
    lon: "",
  },
  "65E": {
    bound: "E",
    en_name: "Fortress Hill",
    tc_name: "炮台山",
    status: "1",
    lag: "",
    lon: "",
  },
  "63E": {
    bound: "E",
    en_name: "Jupiter Street",
    tc_name: "木星街",
    status: "1",
    lag: "",
    lon: "",
  },
  "61E": {
    bound: "E",
    en_name: "Wing Hing Street",
    tc_name: "永興街",
    status: "1",
    lag: "",
    lon: "",
  },
  "59E": {
    bound: "E",
    en_name: "Hing Fat Street",
    tc_name: "興發街",
    status: "1",
    lag: "",
    lon: "",
  },
  "57E": {
    bound: "E",
    en_name: "Victoria Park",
    tc_name: "維多利亞公園",
    status: "1",
    lag: "",
    lon: "",
  },
  "55E": {
    bound: "E",
    en_name: "Shelter Street",
    tc_name: "信德街",
    status: "1",
    lag: "",
    lon: "",
  },
  "53E": {
    bound: "E",
    en_name: "Paterson Street",
    tc_name: "百德新街",
    status: "1",
    lag: "",
    lon: "",
  },
  "51E": {
    bound: "E",
    en_name: "Percival Street",
    tc_name: "波斯富街",
    status: "1",
    lag: "",
    lon: "",
  },
  112: {
    bound: "E",
    en_name: "Tin Lok Lane",
    tc_name: "天樂里",
    status: "1",
    lag: "",
    lon: "",
  },
  111: {
    bound: "E",
    en_name: "Morrison Hill Road",
    tc_name: "摩利臣山道",
    status: "1",
    lag: "",
    lon: "",
  },
  110: {
    bound: "E",
    en_name: "Queen's Road East",
    tc_name: "皇后大道東",
    status: "1",
    lag: "",
    lon: "",
  },
  109: {
    bound: "E",
    en_name: "Hong Kong Cemetery",
    tc_name: "香港墳場",
    status: "1",
    lag: "",
    lon: "",
  },
  HVT_B: {
    bound: "E",
    en_name: "Happy Valley Terminus",
    tc_name: "跑馬地總站",
    status: "1",
    lag: "",
    lon: "",
  },
  108: {
    bound: "E",
    en_name: "Wong Nai Chung Road",
    tc_name: "黃泥涌道",
    status: "1",
    lag: "",
    lon: "",
  },
  107: {
    bound: "E",
    en_name: "Broadwood Road",
    tc_name: "樂活道",
    status: "1",
    lag: "",
    lon: "",
  },
  106: {
    bound: "E",
    en_name: "Leighton Road",
    tc_name: "禮頓道",
    status: "1",
    lag: "",
    lon: "",
  },
  105: {
    bound: "E",
    en_name: "Foo Ming Street",
    tc_name: "富明街",
    status: "1",
    lag: "",
    lon: "",
  },
  "49E": {
    bound: "E",
    en_name: "Canal Road West",
    tc_name: "堅拿道西",
    status: "1",
    lag: "",
    lon: "",
  },
  "47E": {
    bound: "E",
    en_name: "Tonnochy Road",
    tc_name: "杜老誌道",
    status: "1",
    lag: "",
    lon: "",
  },
  "45E": {
    bound: "E",
    en_name: "Fleming Road",
    tc_name: "菲林明道",
    status: "1",
    lag: "",
    lon: "",
  },
  "43E": {
    bound: "E",
    en_name: "O'Brien Road",
    tc_name: "柯布連道",
    status: "1",
    lag: "",
    lon: "",
  },
  "41E": {
    bound: "E",
    en_name: "Luard Road",
    tc_name: "盧押道",
    status: "1",
    lag: "",
    lon: "",
  },
  "39E": {
    bound: "E",
    en_name: "Fenwick Street",
    tc_name: "分域街",
    status: "1",
    lag: "",
    lon: "",
  },
  "37E": {
    bound: "E",
    en_name: "Arsenal Street",
    tc_name: "軍器廠街",
    status: "1",
    lag: "",
    lon: "",
  },
  "35E": {
    bound: "E",
    en_name: "Admiralty MTR Station",
    tc_name: "金鐘港鐵站",
    status: "1",
    lag: "",
    lon: "",
  },
  "33E": {
    bound: "E",
    en_name: "Murray Road",
    tc_name: "美利道",
    status: "1",
    lag: "",
    lon: "",
  },
  "31E": {
    bound: "E",
    en_name: "Bank Street",
    tc_name: "銀行街",
    status: "1",
    lag: "",
    lon: "",
  },
  "29E": {
    bound: "E",
    en_name: "Ice House Street",
    tc_name: "雪廠街",
    status: "1",
    lag: "",
    lon: "",
  },
  "27E": {
    bound: "E",
    en_name: "Pedder Street",
    tc_name: "畢打街",
    status: "1",
    lag: "",
    lon: "",
  },
  "25E": {
    bound: "E",
    en_name: "Jubilee Street",
    tc_name: "租庇利街",
    status: "1",
    lag: "",
    lon: "",
  },
  "23E": {
    bound: "E",
    en_name: "Gilman Street",
    tc_name: "機利文街",
    status: "1",
    lag: "",
    lon: "",
  },
  "21E": {
    bound: "E",
    en_name: "Hillier Street",
    tc_name: "禧利街",
    status: "1",
    lag: "",
    lon: "",
  },
  WMT: {
    bound: "E",
    en_name: "Western Market Terminus",
    tc_name: "上環 (西港城) 總站",
    status: "1",
    lag: "",
    lon: "",
  },
  "19E": {
    bound: "E",
    en_name: "Macau Ferry Terminal",
    tc_name: "港澳碼頭",
    status: "1",
    lag: "",
    lon: "",
  },
  "17E": {
    bound: "E",
    en_name: "Queen Street",
    tc_name: "皇后街",
    status: "1",
    lag: "",
    lon: "",
  },
  "15E": {
    bound: "E",
    en_name: "Eastern Street",
    tc_name: "東邊街",
    status: "1",
    lag: "",
    lon: "",
  },
  "13E": {
    bound: "E",
    en_name: "Western Street",
    tc_name: "西邊街",
    status: "1",
    lag: "",
    lon: "",
  },
  "11E": {
    bound: "E",
    en_name: "Water Street",
    tc_name: "水街",
    status: "1",
    lag: "",
    lon: "",
  },
  "09E": {
    bound: "E",
    en_name: "Whitty Street",
    tc_name: "屈地街",
    status: "1",
    lag: "",
    lon: "",
  },
  WST: {
    bound: "E",
    en_name: "Shek Tong Tsui Terminus",
    tc_name: "石塘咀總站",
    status: "1",
    lag: "",
    lon: "",
  },
  "07E": {
    bound: "E",
    en_name: "Hill Road",
    tc_name: "山道",
    status: "1",
    lag: "",
    lon: "",
  },
  "05E": {
    bound: "E",
    en_name: "Queen's Road West",
    tc_name: "皇后大道西",
    status: "1",
    lag: "",
    lon: "",
  },
  "03E": {
    bound: "E",
    en_name: "Holland Street",
    tc_name: "荷蘭街",
    status: "1",
    lag: "",
    lon: "",
  },
  "01E": {
    bound: "E",
    en_name: "North Street",
    tc_name: "北街",
    status: "1",
    lag: "",
    lon: "",
  },
  KTT: {
    bound: "E",
    en_name: "Kennedy Town Terminus",
    tc_name: "堅尼地城總站",
    status: "1",
    lag: "",
    lon: "",
  },
};

export default { common, hkTramStops };
