const Common = {
  en: {
    UP: "Outbound",
    DOWN: "Inbound",
    arr: "Arriving",
    dep: "Departing",
    min: "min",
    etaAlert:
      "ETA information will be refresh every 10 seconds, reference data only.",
    autoBtnOn: "Auto",
    autoBtnOff: "Auto",
    line: "Line",
    stn: "Station",
    lastUpdate: "Last Update",
    eta: "ETA",
    to: "to ",
    plat: "Platform",
    defaultLine: "Urban Lines",
    saveF: "Save",
    saveT: "Saved",
    routeMap: "Route",
    boundFor: "to",
    ealRAC: "via Racecourse",
  },
  tc: {
    UP: "上行",
    DOWN: "下行",
    arr: "即將抵達",
    dep: "正在離開",
    min: "分鐘",
    etaAlert: "到站時間資訊每10秒自動更新，資料只供參考。",
    autoBtnOn: "自動",
    autoBtnOff: "自動",
    line: "路線",
    stn: "站",
    lastUpdate: "最後更新",
    eta: "到站時間",
    to: "往",
    plat: "月台",
    defaultLine: "市區線",
    saveF: "儲存",
    saveT: "已儲存",
    routeMap: "路線圖",
    boundFor: "往",
    ealRAC: "經馬場",
  },
};

const Error = {
  tc: {
    "NT-205": "本站暫停服務。",
  },
  en: {
    "NT-205": "This Station is Suspended.",
  },
};

const MtrLines = {
  AEL: {
    tc_name: "機場快線",
    en_name: "Airport Express",
    colorCode: "#1c7670",
    stations: ["HOK", "KOW", "TSY", "AIR", "AWE"],
  },
  TCL: {
    tc_name: "東涌線",
    en_name: "Tung Chung Line",
    colorCode: "#fe7f1d",
    stations: ["HOK", "KOW", "OLY", "NAC", "LAK", "TSY", "SUN", "TUC"],
  },

  TKL: {
    tc_name: "將軍澳線",
    en_name: "Tseung Kwan O Line",
    colorCode: "#6b208b",
    stations: ["NOP", "QUB", "YAT", "TIK", "TKO", "LHP", "HAH", "POA"],
  },
  TML: {
    tc_name: "屯馬線",
    en_name: "Tuen Ma Line",
    colorCode: "#9a3b26",
    stations: [
      "WKS",
      "MOS",
      "HEO",
      "TSH",
      "SHM",
      "CIO",
      "STW",
      "CKT",
      "TAW",
      "HIK",
      "DIH",
      "KAT",
      "SUW",
      "TKW",
      "HOM",
      "HUH",
      "ETS",
      "AUS",
      "NAC",
      "MEF",
      "TWW",
      "KSR",
      "YUL",
      "LOP",
      "TIS",
      "SIH",
      "TUM",
    ],
  },
  EAL: {
    tc_name: "東鐵線",
    en_name: "East Rail Line",
    colorCode: "#5eb6e4",
    stations: [
      "LOW",
      "LMC",
      "SHS",
      "FAN",
      "TWO",
      "TAP",
      "UNI",
      "FOT",
      "RAC",
      "SHT",
      "TAW",
      "KOT",
      "MKK",
      "HUH",
      "EXC",
      "ADM",
    ],
  },
  ISL: {
    tc_name: "港島線",
    en_name: "Island Line",
    colorCode: "#0860a8",
  },
  TWL: {
    tc_name: "荃灣綫",
    en_name: "Tsuen Wan Line",
    colorCode: "#ff0000",
  },
  KTL: {
    tc_name: "觀塘綫",
    en_name: "Kwun Tong Line",
    colorCode: "#1a9431",
  },
  DRL: {
    tc_name: "迪士尼線",
    en_name: "Disneyland Resort Line",
    colorCode: "#f550a6",
  },

  SIL: {
    tc_name: "南港島綫",
    en_name: "South Island Line",
    colorCode: "#b5bd00",
  },
  XRL: {
    tc_name: "高速鐵路",
    en_name: "High Speed Rail",
    colorCode: "#9F968C",
  },
  LR: {
    tc_name: "輕鐵",
    en_name: "Light Rail",
    colorCode: "#CD9700",
  },
};

const MtrStations = {
  HOK: {
    tc_name: "香港",
    en_name: "Hong Kong",
    lag: "",
    lon: "",
    interChange: ["TCL", "AEL", "TWL", "ISL"],
    active: "1",
  },
  KOW: {
    tc_name: "九龍",
    en_name: "Kowloon",
    lag: "",
    lon: "",
    interChange: ["TCL", "AEL", "XRL"],
    active: "1",
  },
  TSY: {
    tc_name: "青衣",
    en_name: "Tsing Yi",
    lag: "",
    lon: "",
    interChange: ["TCL", "AEL"],
    active: "1",
  },
  AIR: {
    tc_name: "機場",
    en_name: "Airport",
    lag: "",
    lon: "",
    active: "1",
  },
  AWE: {
    tc_name: "博覽館",
    en_name: "AsiaWorld Expo",
    lag: "",
    lon: "",
    active: "1",
  },
  OLY: {
    tc_name: "奧運",
    en_name: "Olympic",
    lag: "",
    lon: "",
    active: "1",
  },
  NAC: {
    tc_name: "南昌",
    en_name: "Nam Cheong",
    lag: "",
    lon: "",
    interChange: ["TCL", "TML"],
    active: "1",
  },
  LAK: {
    tc_name: "荔景",
    en_name: "Lai King",
    lag: "",
    lon: "",
    interChange: ["TCL", "TWL"],
    active: "1",
  },
  SUN: {
    tc_name: "欣澳",
    en_name: "Sunny Bay",
    lag: "",
    lon: "",
    interChange: ["TCL", "DRL"],
    active: "1",
  },
  TUC: {
    tc_name: "東涌",
    en_name: "Tung Chung",
    lag: "",
    lon: "",
    active: "1",
  },
  WKS: {
    tc_name: "烏溪沙",
    en_name: "Wu Kai Sha",
    lag: "",
    lon: "",
    active: "1",
  },
  MOS: {
    tc_name: "馬鞍山",
    en_name: "Ma On Shan",
    lag: "",
    lon: "",
    active: "1",
  },
  HEO: {
    tc_name: "恆安",
    en_name: "Heng On",
    lag: "",
    lon: "",
    active: "1",
  },
  TSH: {
    tc_name: "大水坑",
    en_name: "Tai Shui Hang",
    lag: "",
    lon: "",
    active: "1",
  },
  SHM: {
    tc_name: "石門",
    en_name: "Shek Mun",
    lag: "",
    lon: "",
    active: "1",
  },
  CIO: {
    tc_name: "第一城",
    en_name: "City One",
    lag: "",
    lon: "",
    active: "1",
  },
  STW: {
    tc_name: "沙田圍",
    en_name: "Sha Tin Wai",
    lag: "",
    lon: "",
    active: "1",
  },
  CKT: {
    tc_name: "車公廟",
    en_name: "Che Kung Temple",
    lag: "",
    lon: "",
    active: "1",
  },
  TAW: {
    tc_name: "大圍",
    en_name: "Tai Wai",
    lag: "",
    lon: "",
    active: "1",
  },
  HIK: {
    tc_name: "顯徑",
    en_name: "Hin Keng",
    lag: "",
    lon: "",
    active: "1",
  },
  DIH: {
    tc_name: "鑽石山",
    en_name: "Diamond Hill",
    lag: "",
    lon: "",
    active: "1",
  },
  KAT: {
    tc_name: "啟德",
    en_name: "Kai Tak",
    lag: "",
    lon: "",
    active: "1",
  },
  SUW: {
    tc_name: "宋皇臺",
    en_name: "Sung Wong Toi",
    lag: "",
    lon: "",
    active: "1",
  },
  TKW: {
    tc_name: "土瓜灣",
    en_name: "To Kwa Wan",
    lag: "",
    lon: "",
    active: "1",
  },
  HOM: {
    tc_name: "何文田",
    en_name: "Ho Man Tin",
    lag: "",
    lon: "",
    active: "1",
  },
  HUH: {
    tc_name: "紅磡",
    en_name: "Hung Hom",
    lag: "",
    lon: "",
    active: "1",
  },
  ETS: {
    tc_name: "尖東",
    en_name: "East Tsim Sha Tsui",
    lag: "",
    lon: "",
    active: "1",
  },
  AUS: {
    tc_name: "柯士甸",
    en_name: "Austin",
    lag: "",
    lon: "",
    active: "1",
  },
  MEF: {
    tc_name: "美孚",
    en_name: "Mei Foo",
    lag: "",
    lon: "",
    active: "1",
  },
  TWW: {
    tc_name: "荃灣西",
    en_name: "Tsuen Wan West",
    lag: "",
    lon: "",
    active: "1",
  },
  KSR: {
    tc_name: "錦上路",
    en_name: "Kam Sheung Road",
    lag: "",
    lon: "",
    active: "1",
  },
  YUL: {
    tc_name: "元朗",
    en_name: "Yuen Long",
    lag: "",
    lon: "",
    active: "1",
  },
  LOP: {
    tc_name: "朗屏",
    en_name: "Long Ping",
    lag: "",
    lon: "",
    active: "1",
  },
  TIS: {
    tc_name: "天水圍",
    en_name: "Tin Shui Wai",
    lag: "",
    lon: "",
    active: "1",
  },
  SIH: {
    tc_name: "兆康",
    en_name: "Siu Hong",
    lag: "",
    lon: "",
    active: "1",
  },
  TUM: {
    tc_name: "屯門",
    en_name: "Tuen Mun",
    lag: "",
    lon: "",
    active: "1",
  },
  NOP: {
    tc_name: "北角",
    en_name: "North Point",
    lag: "",
    lon: "",
    active: "1",
  },
  QUB: {
    tc_name: "鰂魚涌",
    en_name: "Quarry Bay",
    lag: "",
    lon: "",
    active: "1",
  },
  YAT: {
    tc_name: "油塘",
    en_name: "Yau Tong",
    lag: "",
    lon: "",
    active: "1",
  },
  TIK: {
    tc_name: "調景嶺",
    en_name: "Tiu Keng Leng",
    lag: "",
    lon: "",
    active: "1",
  },
  TKO: {
    tc_name: "將軍澳",
    en_name: "Tseung Kwan O",
    lag: "",
    lon: "",
    active: "1",
  },
  LHP: {
    tc_name: "康城",
    en_name: "LOHAS Park",
    lag: "",
    lon: "",
    active: "1",
  },
  HAH: {
    tc_name: "坑口",
    en_name: "Hang Hau",
    lag: "",
    lon: "",
    active: "1",
  },
  POA: {
    tc_name: "寶琳",
    en_name: "Po Lam",
    lag: "",
    lon: "",
    active: "1",
  },
  LMC: {
    tc_name: "落馬洲",
    en_name: "Lok Ma Chau",
    lag: "",
    lon: "",
    active: "1",
  },
  LOW: {
    tc_name: "羅湖",
    en_name: "Lo Wu",
    lag: "",
    lon: "",
    active: "1",
  },
  SHS: {
    tc_name: "上水",
    en_name: "Sheung Shui",
    lag: "",
    lon: "",
    active: "1",
  },
  FAN: {
    tc_name: "粉嶺",
    en_name: "Fanling",
    lag: "",
    lon: "",
    active: "1",
  },
  TWO: {
    tc_name: "太和",
    en_name: "Tai Wo",
    lag: "",
    lon: "",
    active: "1",
  },
  TAP: {
    tc_name: "大埔墟",
    en_name: "Tai Po Market",
    lag: "",
    lon: "",
    active: "1",
  },
  UNI: {
    tc_name: "大學",
    en_name: "University",
    lag: "",
    lon: "",
    active: "1",
  },
  RAC: {
    tc_name: "馬場",
    en_name: "Racecourse",
    lag: "",
    lon: "",
    active: "1",
  },
  FOT: {
    tc_name: "火炭",
    en_name: "Fo Tan",
    lag: "",
    lon: "",
    active: "1",
  },
  SHT: {
    tc_name: "沙田",
    en_name: "Sha Tin",
    lag: "",
    lon: "",
    active: "1",
  },
  KOT: {
    tc_name: "九龍塘",
    en_name: "Kowloon Tong",
    lag: "",
    lon: "",
    active: "1",
  },
  MKK: {
    tc_name: "旺角東",
    en_name: "Mong Kok East",
    lag: "",
    lon: "",
    active: "1",
  },
  EXC: {
    tc_name: "會展",
    en_name: "Exhibition Centre",
    lag: "",
    lon: "",
    active: "1",
  },
  ADM: {
    tc_name: "金鐘",
    en_name: "Admiralty",
    lag: "",
    lon: "",
    active: "1",
  },
};

export default { Common, MtrLines, MtrStations, Error };
